// Chesser achievements: 40 topics x 5 = 200 achievements.
// Each entry is [name, description, stat, need]; it unlocks when the player's value for
// `stat` reaches `need`. app.js computes stat values and tracks unlocks. Loaded before app.js.
window.ACH_TOPICS = [
  { t: 'Moves', icon: '👣', a: [
    ['First Move', 'Make your first move', 'moves', 1],
    ['Mover', 'Make 100 moves', 'moves', 100],
    ['Busy', 'Make 500 moves', 'moves', 500],
    ['Move Machine', 'Make 2000 moves', 'moves', 2000],
    ['Move Legend', 'Make 10000 moves', 'moves', 10000] ] },
  { t: 'Games', icon: '🎮', a: [
    ['First Game', 'Play a game', 'games', 1],
    ['Getting Into It', 'Play 10 games', 'games', 10],
    ['Regular', 'Play 50 games', 'games', 50],
    ['Veteran', 'Play 150 games', 'games', 150],
    ['Addicted', 'Play 400 games', 'games', 400] ] },
  { t: 'Wins', icon: '🏆', a: [
    ['First Win', 'Win a game', 'wins', 1],
    ['Winning', 'Win 5 games', 'wins', 5],
    ['Winner', 'Win 25 games', 'wins', 25],
    ['Champion', 'Win 100 games', 'wins', 100],
    ['Conqueror', 'Win 300 games', 'wins', 300] ] },
  { t: 'Captures', icon: '⚔️', a: [
    ['First Capture', 'Capture a piece', 'captures', 1],
    ['Grabber', 'Capture 25 pieces', 'captures', 25],
    ['Hunter', 'Capture 100 pieces', 'captures', 100],
    ['Predator', 'Capture 500 pieces', 'captures', 500],
    ['Apex', 'Capture 2000 pieces', 'captures', 2000] ] },
  { t: 'Checks', icon: '➕', a: [
    ['Check!', 'Give a check', 'checks', 1],
    ['Nagging', 'Give 25 checks', 'checks', 25],
    ['Pressure', 'Give 100 checks', 'checks', 100],
    ['Relentless', 'Give 300 checks', 'checks', 300],
    ['Check Storm', 'Give 750 checks', 'checks', 750] ] },
  { t: 'Checkmates', icon: '♚', a: [
    ['Checkmate!', 'Deliver a checkmate', 'checkmates', 1],
    ['Closer', 'Deliver 5 checkmates', 'checkmates', 5],
    ['Finisher', 'Deliver 25 checkmates', 'checkmates', 25],
    ['Executioner', 'Deliver 100 checkmates', 'checkmates', 100],
    ['Terminator', 'Deliver 300 checkmates', 'checkmates', 300] ] },
  { t: 'Castling', icon: '🏰', a: [
    ['Castle Up', 'Castle once', 'castles', 1],
    ['Tucked In', 'Castle 10 times', 'castles', 10],
    ['Safe King', 'Castle 50 times', 'castles', 50],
    ['Fortress', 'Castle 150 times', 'castles', 150],
    ['Impenetrable', 'Castle 500 times', 'castles', 500] ] },
  { t: 'Promotions', icon: '👑', a: [
    ['New Queen', 'Promote a pawn', 'promotions', 1],
    ['Upgrader', 'Promote 5 pawns', 'promotions', 5],
    ['Promoter', 'Promote 25 pawns', 'promotions', 25],
    ['Royalty', 'Promote 100 pawns', 'promotions', 100],
    ['Coronation', 'Promote 300 pawns', 'promotions', 300] ] },
  { t: 'Speed', icon: '🏃', a: [
    ['Fast Win', 'Win in 30 moves or fewer', 'win30', 1],
    ['Faster Win', 'Win in 25 moves or fewer', 'win25', 1],
    ['Quick Win', 'Win in 20 moves or fewer', 'win20', 1],
    ['Speedy Win', 'Win in 15 moves or fewer', 'win15', 1],
    ['Blitz Win', 'Win in 10 moves or fewer', 'win10', 1] ] },
  { t: 'Mate Puzzles', icon: '♟️', a: [
    ['Mate Solver', 'Solve a mate puzzle', 'puz_mate', 1],
    ['Mate Fan', 'Solve 10 mate puzzles', 'puz_mate', 10],
    ['Mate Master', 'Solve 50 mate puzzles', 'puz_mate', 50],
    ['Mate Legend', 'Solve 150 mate puzzles', 'puz_mate', 150],
    ['Mate God', 'Solve 400 mate puzzles', 'puz_mate', 400] ] },
  { t: 'Tactic Puzzles', icon: '🎯', a: [
    ['Tactician', 'Solve a tactic puzzle', 'puz_tactic', 1],
    ['Tactic Fan', 'Solve 10 tactic puzzles', 'puz_tactic', 10],
    ['Sharp Eye', 'Solve 50 tactic puzzles', 'puz_tactic', 50],
    ['Tactics Legend', 'Solve 150 tactic puzzles', 'puz_tactic', 150],
    ['Tactics God', 'Solve 400 tactic puzzles', 'puz_tactic', 400] ] },
  { t: 'Endgame Puzzles', icon: '🔚', a: [
    ['Endgame Rookie', 'Solve an endgame puzzle', 'puz_endgame', 1],
    ['Endgame Fan', 'Solve 10 endgame puzzles', 'puz_endgame', 10],
    ['Endgame Pro', 'Solve 50 endgame puzzles', 'puz_endgame', 50],
    ['Endgame Legend', 'Solve 150 endgame puzzles', 'puz_endgame', 150],
    ['Endgame God', 'Solve 400 endgame puzzles', 'puz_endgame', 400] ] },
  { t: 'Puzzle Count', icon: '🧩', a: [
    ['Puzzler', 'Solve 10 puzzles', 'puz', 10],
    ['Puzzle Fan', 'Solve 50 puzzles', 'puz', 50],
    ['Puzzle Pro', 'Solve 200 puzzles', 'puz', 200],
    ['Puzzle Master', 'Solve 750 puzzles', 'puz', 750],
    ['Puzzle Titan', 'Solve 2000 puzzles', 'puz', 2000] ] },
  { t: 'Easy Puzzles', icon: '🟢', a: [
    ['Easy Start', 'Solve 5 easy puzzles', 'puz_easy', 5],
    ['Easy 25', 'Solve 25 easy puzzles', 'puz_easy', 25],
    ['Easy 75', 'Solve 75 easy puzzles', 'puz_easy', 75],
    ['Easy 200', 'Solve 200 easy puzzles', 'puz_easy', 200],
    ['Easy Master', 'Solve 450 easy puzzles', 'puz_easy', 450] ] },
  { t: 'Normal Puzzles', icon: '🟡', a: [
    ['Stepping Up', 'Solve 5 normal puzzles', 'puz_normal', 5],
    ['Normal 25', 'Solve 25 normal puzzles', 'puz_normal', 25],
    ['Normal 75', 'Solve 75 normal puzzles', 'puz_normal', 75],
    ['Normal 200', 'Solve 200 normal puzzles', 'puz_normal', 200],
    ['Normal Master', 'Solve 450 normal puzzles', 'puz_normal', 450] ] },
  { t: 'Hard Puzzles', icon: '🔴', a: [
    ['Brave', 'Solve 5 hard puzzles', 'puz_hard', 5],
    ['Hard 25', 'Solve 25 hard puzzles', 'puz_hard', 25],
    ['Hard 75', 'Solve 75 hard puzzles', 'puz_hard', 75],
    ['Hard 200', 'Solve 200 hard puzzles', 'puz_hard', 200],
    ['Hard Master', 'Solve 450 hard puzzles', 'puz_hard', 450] ] },
  { t: 'Clean Solves', icon: '✨', a: [
    ['No Hint', 'Solve a puzzle cleanly', 'puzClean', 1],
    ['Clean 10', 'Solve 10 puzzles cleanly', 'puzClean', 10],
    ['Clean 50', 'Solve 50 puzzles cleanly', 'puzClean', 50],
    ['Flawless', 'Solve 200 puzzles cleanly', 'puzClean', 200],
    ['Perfect', 'Solve 500 puzzles cleanly', 'puzClean', 500] ] },
  { t: 'Puzzle Streak', icon: '🔥', a: [
    ['On a Roll', 'Get a 3 puzzle streak', 'puzStreakBest', 3],
    ['Warm', 'Get an 8 puzzle streak', 'puzStreakBest', 8],
    ['Hot Streak', 'Get a 15 puzzle streak', 'puzStreakBest', 15],
    ['Unstoppable', 'Get a 30 puzzle streak', 'puzStreakBest', 30],
    ['Inferno', 'Get a 60 puzzle streak', 'puzStreakBest', 60] ] },
  { t: 'Daily Streak', icon: '📅', a: [
    ['Three Days', 'Reach a 3-day streak', 'streakBest', 3],
    ['One Week', 'Reach a 7-day streak', 'streakBest', 7],
    ['One Month', 'Reach a 30-day streak', 'streakBest', 30],
    ['Hundred Days', 'Reach a 100-day streak', 'streakBest', 100],
    ['One Year', 'Reach a 365-day streak', 'streakBest', 365] ] },
  { t: 'Bots', icon: '👾', a: [
    ['Bot Beater', 'Beat a bot', 'botsBeaten', 1],
    ['Bot Trio', 'Beat 3 different bots', 'botsBeaten', 3],
    ['Bot Hunter', 'Beat 7 different bots', 'botsBeaten', 7],
    ['Bot Slayer', 'Beat 12 different bots', 'botsBeaten', 12],
    ['Bot Master', 'Beat 18 different bots', 'botsBeaten', 18] ] },
  { t: 'AI Wins', icon: '🤖', a: [
    ['Beat the AI', 'Win vs the AI', 'winsAI', 1],
    ['AI Beater', 'Win 5 AI games', 'winsAI', 5],
    ['AI Crusher', 'Win 20 AI games', 'winsAI', 20],
    ['AI Overlord', 'Win 60 AI games', 'winsAI', 60],
    ['AI Nemesis', 'Win 150 AI games', 'winsAI', 150] ] },
  { t: 'Online', icon: '🌐', a: [
    ['Go Online', 'Play an online game', 'onlineGames', 1],
    ['Online Three', 'Play 3 online games', 'onlineGames', 3],
    ['Online Ten', 'Play 10 online games', 'onlineGames', 10],
    ['Online 25', 'Play 25 online games', 'onlineGames', 25],
    ['Online 60', 'Play 60 online games', 'onlineGames', 60] ] },
  { t: 'Friends', icon: '🤝', a: [
    ['Play a Friend', 'Play a pass-and-play game', 'friendsGames', 1],
    ['Friendly Three', 'Play 3 friend games', 'friendsGames', 3],
    ['Friendly Ten', 'Play 10 friend games', 'friendsGames', 10],
    ['Friendly 25', 'Play 25 friend games', 'friendsGames', 25],
    ['Friendly 60', 'Play 60 friend games', 'friendsGames', 60] ] },
  { t: 'Collection', icon: '🎁', a: [
    ['Collector', 'Collect 5 items', 'collection', 5],
    ['Gatherer', 'Collect 20 items', 'collection', 20],
    ['Hoarder', 'Collect 50 items', 'collection', 50],
    ['Curator', 'Collect 100 items', 'collection', 100],
    ['Museum', 'Collect 200 items', 'collection', 200] ] },
  { t: 'Rare Finds', icon: '💎', a: [
    ['Rare Find', 'Get a rare item or better', 'rares', 1],
    ['Rare Five', 'Get 5 rare items or better', 'rares', 5],
    ['Rare 15', 'Get 15 rare items or better', 'rares', 15],
    ['Legendary!', 'Get a legendary item', 'legendary', 1],
    ['Rare Hoard', 'Get 40 rare items or better', 'rares', 40] ] },
  { t: 'Packs', icon: '📦', a: [
    ['Pack Opener', 'Open a pack', 'packs', 1],
    ['Pack Ten', 'Open 10 packs', 'packs', 10],
    ['Pack 30', 'Open 30 packs', 'packs', 30],
    ['Pack 80', 'Open 80 packs', 'packs', 80],
    ['Pack 200', 'Open 200 packs', 'packs', 200] ] },
  { t: 'Basics', icon: '🎓', a: [
    ['Student', 'Finish a basic skill', 'lessonsBasics', 1],
    ['Apprentice', 'Finish 3 basic skills', 'lessonsBasics', 3],
    ['Scholar', 'Finish 5 basic skills', 'lessonsBasics', 5],
    ['Almost There', 'Finish 8 basic skills', 'lessonsBasics', 8],
    ['Graduate', 'Finish all 10 basic skills', 'lessonsBasics', 10] ] },
  { t: 'Levels', icon: '🌟', a: [
    ['Level One', 'Complete a level', 'levelsDone', 1],
    ['Level Two', 'Complete 2 levels', 'levelsDone', 2],
    ['Level Three', 'Complete 3 levels', 'levelsDone', 3],
    ['Level Four', 'Complete 4 levels', 'levelsDone', 4],
    ['All Levels', 'Complete all 5 levels', 'levelsDone', 5] ] },
  { t: 'Tom', icon: '🐐', a: [
    ['Say Hi to Tom', 'Send Tom a message', 'tomChats', 1],
    ['Tom\'s Buddy', 'Send Tom 10 messages', 'tomChats', 10],
    ['Tom\'s BFF', 'Send Tom 50 messages', 'tomChats', 50],
    ['Face the GOAT', 'Play a game vs Tom', 'tomPlayed', 1],
    ['Tom Superfan', 'Play Tom 10 times', 'tomPlayed', 10] ] },
  { t: 'World Chat', icon: '🗣️', a: [
    ['Hello World', 'Send a world chat message', 'worldChats', 1],
    ['Chatty', 'Send 5 world messages', 'worldChats', 5],
    ['Chatterbox', 'Send 20 world messages', 'worldChats', 20],
    ['Social', 'Send 50 world messages', 'worldChats', 50],
    ['Town Crier', 'Send 100 world messages', 'worldChats', 100] ] },
  { t: 'Analyzer', icon: '🔍', a: [
    ['Analyst', 'Analyze a position', 'analyzed', 1],
    ['Reviewer', 'Analyze 5 times', 'analyzed', 5],
    ['Studious', 'Analyze 15 times', 'analyzed', 15],
    ['Deep Diver', 'Analyze 40 times', 'analyzed', 40],
    ['Grandmaster Eye', 'Analyze 100 times', 'analyzed', 100] ] },
  { t: 'Rating', icon: '📈', a: [
    ['Rated', 'Play a rated game', 'rated', 1],
    ['Climber', 'Reach a 1000 rating', 'ratingPeak', 1000],
    ['Skilled', 'Reach a 1200 rating', 'ratingPeak', 1200],
    ['Expert', 'Reach a 1400 rating', 'ratingPeak', 1400],
    ['Master', 'Reach a 1600 rating', 'ratingPeak', 1600] ] },
  { t: 'Membership', icon: '🎖️', a: [
    ['Sign Up', 'Create an account', 'account', 1],
    ['Bronze', 'Become a Bronze member', 'tier', 1],
    ['Silver', 'Become a Silver member', 'tier', 2],
    ['Gold', 'Become a Gold member', 'tier', 3],
    ['Loyal', 'Play 100 games', 'games', 100] ] },
  { t: 'Explorer', icon: '🧭', a: [
    ['Curious', 'Try 2 game modes', 'modesPlayed', 2],
    ['Wanderer', 'Try 4 game modes', 'modesPlayed', 4],
    ['Adventurer', 'Try 6 game modes', 'modesPlayed', 6],
    ['Globetrotter', 'Try 8 game modes', 'modesPlayed', 8],
    ['Explorer', 'Try all 9 modes', 'modesPlayed', 9] ] },
  { t: 'Draws', icon: '½', a: [
    ['Stalemate', 'Draw a game', 'draws', 1],
    ['Peaceful', 'Draw 3 games', 'draws', 3],
    ['Diplomat', 'Draw 10 games', 'draws', 10],
    ['Negotiator', 'Draw 25 games', 'draws', 25],
    ['Peacekeeper', 'Draw 50 games', 'draws', 50] ] },
  { t: 'Persistence', icon: '💪', a: [
    ['Keep Going', 'Play through 5 losses', 'losses', 5],
    ['Determined', 'Play through 25 losses', 'losses', 25],
    ['Never Quit', 'Play through 50 losses', 'losses', 50],
    ['Resilient', 'Play through 100 losses', 'losses', 100],
    ['Unbreakable', 'Play through 200 losses', 'losses', 200] ] },
  { t: 'Marathon', icon: '🏅', a: [
    ['Marathon', 'Play 50 games', 'games', 50],
    ['Double Marathon', 'Play 150 games', 'games', 150],
    ['Iron Player', 'Play 300 games', 'games', 300],
    ['Ultra', 'Play 600 games', 'games', 600],
    ['Legendary Grind', 'Play 1200 games', 'games', 1200] ] },
  { t: 'Grinder', icon: '⏳', a: [
    ['Warming Up', 'Make 2000 moves', 'moves', 2000],
    ['Grinding', 'Make 5000 moves', 'moves', 5000],
    ['Heavy Grind', 'Make 15000 moves', 'moves', 15000],
    ['Machine', 'Make 30000 moves', 'moves', 30000],
    ['Unstoppable Grind', 'Make 60000 moves', 'moves', 60000] ] },
  { t: 'Puzzle Legend', icon: '🏵️', a: [
    ['Puzzle Hundred', 'Solve 100 puzzles', 'puz', 100],
    ['Puzzle 400', 'Solve 400 puzzles', 'puz', 400],
    ['Puzzle 1000', 'Solve 1000 puzzles', 'puz', 1000],
    ['Puzzle 2500', 'Solve 2500 puzzles', 'puz', 2500],
    ['Puzzle Legend', 'Solve 5000 puzzles', 'puz', 5000] ] },
  { t: 'Trophies', icon: '🏆', a: [
    ['Achiever', 'Unlock 25 achievements', 'unlocked', 25],
    ['Trophy Hunter', 'Unlock 75 achievements', 'unlocked', 75],
    ['Trophy Master', 'Unlock 125 achievements', 'unlocked', 125],
    ['Trophy Legend', 'Unlock 170 achievements', 'unlocked', 170],
    ['Completionist', 'Unlock 195 achievements', 'unlocked', 195] ] },
];
